name: weathernet
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - brotli-python=1.2.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - expat=2.7.4
  - ffmpeg=4.2.2
  - filelock=3.20.3
  - freetype=2.14.1
  - fsspec=2026.1.0
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.2
  - gnutls=3.6.15
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - jpeg=9f
  - kernel-headers_linux-64=4.18.0
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250814.1
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnsl=2.0.0
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopus=1.6.1
  - libpng=1.6.54
  - libprotobuf=6.33.0
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.21.0
  - libtiff=4.5.1
  - libtorch=2.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.7.3
  - networkx=3.4.2
  - numpy-base=1.26.4
  - ocl-icd=2.3.3
  - opencl-headers=2025.07.22
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.19
  - opentelemetry-api=1.38.0
  - packaging=25.0
  - pillow=11.1.0
  - pip=25.3
  - pthread-stubs=0.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.10.1
  - sleef=3.5.1
  - sqlite=3.51.1
  - sysroot_linux-64=2.28
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - wheel=0.46.3
  - x264=1!157.20191217
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.4.0
      - grpcio==1.78.0
      - h5py==3.15.1
      - markdown==3.10.1
      - numpy==1.24.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - protobuf==6.33.5
      - pybase64==1.4.3
      - pytorch-ignite==0.5.3
      - ros2-numpy==0.0.5
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.3
      - transformations==2025.1.1
      - triton==3.1.0
      - werkzeug==3.1.5
      - wget==3.2
      - wrapt==2.1.1
prefix: /home/ubuntu/miniconda3/envs/weathernet
